fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -80,12 +80,16 @@ jobs:
         chmod 600 ~/.ssh/id_rsa
         sudo chmod 666 /var/run/docker.sock
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$SERVER << EOF
-          cd /myservices/fs
-          echo "$SUDO_PASSWORD" | sudo -S docker-compose down
-          sudo docker ps -a -q --filter name=app_container | xargs --no-run-if-empty sudo docker rm
-          sudo docker ps -a -q --filter name=script_container | xargs --no-run-if-empty sudo docker rm
+          cd /myservices/fs || exit 1
+          if [ ! -f docker-compose.yml ]; then
+            echo "docker-compose.yml not found"
+            exit 1
+          fi
+          echo "$SUDO_PASSWORD" | sudo -S docker-compose down || true
+          sudo docker ps -a -q --filter name=app_container | xargs --no-run-if-empty sudo docker rm || true
+          sudo docker ps -a -q --filter name=script_container | xargs --no-run-if-empty sudo docker rm || true
           echo "$SUDO_PASSWORD" | sudo -S docker rmi mimasiunia/filesshare_app:latest || true
           echo "$SUDO_PASSWORD" | sudo -S docker rmi mimasiunia/filesshare_script:latest || true
-          echo "$SUDO_PASSWORD" | sudo -S docker-compose pull
-          echo "$SUDO_PASSWORD" | sudo -S docker-compose up -d
+          echo "$SUDO_PASSWORD" | sudo -S docker-compose pull || exit 1
+          echo "$SUDO_PASSWORD" | sudo -S docker-compose up -d || exit 1
         EOF
